/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public interface LibusbConstants {
  public final static int LIBUSB_PATH_MAX = LibusbJNI.get_LIBUSB_PATH_MAX();
  public final static int USB_CLASS_PER_INTERFACE = LibusbJNI.get_USB_CLASS_PER_INTERFACE();
  public final static int USB_CLASS_AUDIO = LibusbJNI.get_USB_CLASS_AUDIO();
  public final static int USB_CLASS_COMM = LibusbJNI.get_USB_CLASS_COMM();
  public final static int USB_CLASS_HID = LibusbJNI.get_USB_CLASS_HID();
  public final static int USB_CLASS_PRINTER = LibusbJNI.get_USB_CLASS_PRINTER();
  public final static int USB_CLASS_MASS_STORAGE = LibusbJNI.get_USB_CLASS_MASS_STORAGE();
  public final static int USB_CLASS_HUB = LibusbJNI.get_USB_CLASS_HUB();
  public final static int USB_CLASS_DATA = LibusbJNI.get_USB_CLASS_DATA();
  public final static int USB_CLASS_VENDOR_SPEC = LibusbJNI.get_USB_CLASS_VENDOR_SPEC();
  public final static int USB_DT_DEVICE = LibusbJNI.get_USB_DT_DEVICE();
  public final static int USB_DT_CONFIG = LibusbJNI.get_USB_DT_CONFIG();
  public final static int USB_DT_STRING = LibusbJNI.get_USB_DT_STRING();
  public final static int USB_DT_INTERFACE = LibusbJNI.get_USB_DT_INTERFACE();
  public final static int USB_DT_ENDPOINT = LibusbJNI.get_USB_DT_ENDPOINT();
  public final static int USB_DT_HID = LibusbJNI.get_USB_DT_HID();
  public final static int USB_DT_REPORT = LibusbJNI.get_USB_DT_REPORT();
  public final static int USB_DT_PHYSICAL = LibusbJNI.get_USB_DT_PHYSICAL();
  public final static int USB_DT_HUB = LibusbJNI.get_USB_DT_HUB();
  public final static int USB_DT_DEVICE_SIZE = LibusbJNI.get_USB_DT_DEVICE_SIZE();
  public final static int USB_DT_CONFIG_SIZE = LibusbJNI.get_USB_DT_CONFIG_SIZE();
  public final static int USB_DT_INTERFACE_SIZE = LibusbJNI.get_USB_DT_INTERFACE_SIZE();
  public final static int USB_DT_ENDPOINT_SIZE = LibusbJNI.get_USB_DT_ENDPOINT_SIZE();
  public final static int USB_DT_ENDPOINT_AUDIO_SIZE = LibusbJNI.get_USB_DT_ENDPOINT_AUDIO_SIZE();
  public final static int USB_DT_HUB_NONVAR_SIZE = LibusbJNI.get_USB_DT_HUB_NONVAR_SIZE();
  public final static int USB_MAXENDPOINTS = LibusbJNI.get_USB_MAXENDPOINTS();
  public final static int USB_ENDPOINT_ADDRESS_MASK = LibusbJNI.get_USB_ENDPOINT_ADDRESS_MASK();
  public final static int USB_ENDPOINT_DIR_MASK = LibusbJNI.get_USB_ENDPOINT_DIR_MASK();
  public final static int USB_ENDPOINT_TYPE_MASK = LibusbJNI.get_USB_ENDPOINT_TYPE_MASK();
  public final static int USB_ENDPOINT_TYPE_CONTROL = LibusbJNI.get_USB_ENDPOINT_TYPE_CONTROL();
  public final static int USB_ENDPOINT_TYPE_ISOCHRONOUS = LibusbJNI.get_USB_ENDPOINT_TYPE_ISOCHRONOUS();
  public final static int USB_ENDPOINT_TYPE_BULK = LibusbJNI.get_USB_ENDPOINT_TYPE_BULK();
  public final static int USB_ENDPOINT_TYPE_INTERRUPT = LibusbJNI.get_USB_ENDPOINT_TYPE_INTERRUPT();
  public final static int USB_MAXINTERFACES = LibusbJNI.get_USB_MAXINTERFACES();
  public final static int USB_MAXALTSETTING = LibusbJNI.get_USB_MAXALTSETTING();
  public final static int USB_MAXCONFIG = LibusbJNI.get_USB_MAXCONFIG();
  public final static int USB_REQ_GET_STATUS = LibusbJNI.get_USB_REQ_GET_STATUS();
  public final static int USB_REQ_CLEAR_FEATURE = LibusbJNI.get_USB_REQ_CLEAR_FEATURE();
  public final static int USB_REQ_SET_FEATURE = LibusbJNI.get_USB_REQ_SET_FEATURE();
  public final static int USB_REQ_SET_ADDRESS = LibusbJNI.get_USB_REQ_SET_ADDRESS();
  public final static int USB_REQ_GET_DESCRIPTOR = LibusbJNI.get_USB_REQ_GET_DESCRIPTOR();
  public final static int USB_REQ_SET_DESCRIPTOR = LibusbJNI.get_USB_REQ_SET_DESCRIPTOR();
  public final static int USB_REQ_GET_CONFIGURATION = LibusbJNI.get_USB_REQ_GET_CONFIGURATION();
  public final static int USB_REQ_SET_CONFIGURATION = LibusbJNI.get_USB_REQ_SET_CONFIGURATION();
  public final static int USB_REQ_GET_INTERFACE = LibusbJNI.get_USB_REQ_GET_INTERFACE();
  public final static int USB_REQ_SET_INTERFACE = LibusbJNI.get_USB_REQ_SET_INTERFACE();
  public final static int USB_REQ_SYNCH_FRAME = LibusbJNI.get_USB_REQ_SYNCH_FRAME();
  public final static int USB_TYPE_STANDARD = LibusbJNI.get_USB_TYPE_STANDARD();
  public final static int USB_TYPE_CLASS = LibusbJNI.get_USB_TYPE_CLASS();
  public final static int USB_TYPE_VENDOR = LibusbJNI.get_USB_TYPE_VENDOR();
  public final static int USB_TYPE_RESERVED = LibusbJNI.get_USB_TYPE_RESERVED();
  public final static int USB_RECIP_DEVICE = LibusbJNI.get_USB_RECIP_DEVICE();
  public final static int USB_RECIP_INTERFACE = LibusbJNI.get_USB_RECIP_INTERFACE();
  public final static int USB_RECIP_ENDPOINT = LibusbJNI.get_USB_RECIP_ENDPOINT();
  public final static int USB_RECIP_OTHER = LibusbJNI.get_USB_RECIP_OTHER();
  public final static int USB_ENDPOINT_IN = LibusbJNI.get_USB_ENDPOINT_IN();
  public final static int USB_ENDPOINT_OUT = LibusbJNI.get_USB_ENDPOINT_OUT();
  public final static int USB_ERROR_BEGIN = LibusbJNI.get_USB_ERROR_BEGIN();
}
