/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_config_descriptor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_config_descriptor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_config_descriptor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_config_descriptor(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBLength(short value) {
    LibusbJNI.usb_config_descriptor_bLength_set(swigCPtr, this, value);
  }

  public short getBLength() {
    return LibusbJNI.usb_config_descriptor_bLength_get(swigCPtr, this);
  }

  public void setBDescriptorType(short value) {
    LibusbJNI.usb_config_descriptor_bDescriptorType_set(swigCPtr, this, value);
  }

  public short getBDescriptorType() {
    return LibusbJNI.usb_config_descriptor_bDescriptorType_get(swigCPtr, this);
  }

  public void setWTotalLength(int value) {
    LibusbJNI.usb_config_descriptor_wTotalLength_set(swigCPtr, this, value);
  }

  public int getWTotalLength() {
    return LibusbJNI.usb_config_descriptor_wTotalLength_get(swigCPtr, this);
  }

  public void setBNumInterfaces(short value) {
    LibusbJNI.usb_config_descriptor_bNumInterfaces_set(swigCPtr, this, value);
  }

  public short getBNumInterfaces() {
    return LibusbJNI.usb_config_descriptor_bNumInterfaces_get(swigCPtr, this);
  }

  public void setBConfigurationValue(short value) {
    LibusbJNI.usb_config_descriptor_bConfigurationValue_set(swigCPtr, this, value);
  }

  public short getBConfigurationValue() {
    return LibusbJNI.usb_config_descriptor_bConfigurationValue_get(swigCPtr, this);
  }

  public void setIConfiguration(short value) {
    LibusbJNI.usb_config_descriptor_iConfiguration_set(swigCPtr, this, value);
  }

  public short getIConfiguration() {
    return LibusbJNI.usb_config_descriptor_iConfiguration_get(swigCPtr, this);
  }

  public void setBmAttributes(short value) {
    LibusbJNI.usb_config_descriptor_bmAttributes_set(swigCPtr, this, value);
  }

  public short getBmAttributes() {
    return LibusbJNI.usb_config_descriptor_bmAttributes_get(swigCPtr, this);
  }

  public void setMaxPower(short value) {
    LibusbJNI.usb_config_descriptor_MaxPower_set(swigCPtr, this, value);
  }

  public short getMaxPower() {
    return LibusbJNI.usb_config_descriptor_MaxPower_get(swigCPtr, this);
  }

  public void set_interface(usb_interface value) {
    LibusbJNI.usb_config_descriptor__interface_set(swigCPtr, this, usb_interface.getCPtr(value), value);
  }

  public usb_interface get_interface() {
    long cPtr = LibusbJNI.usb_config_descriptor__interface_get(swigCPtr, this);
    return (cPtr == 0) ? null : new usb_interface(cPtr, false);
  }

  public void setExtra(SWIGTYPE_p_unsigned_char value) {
    LibusbJNI.usb_config_descriptor_extra_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getExtra() {
    long cPtr = LibusbJNI.usb_config_descriptor_extra_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setExtralen(int value) {
    LibusbJNI.usb_config_descriptor_extralen_set(swigCPtr, this, value);
  }

  public int getExtralen() {
    return LibusbJNI.usb_config_descriptor_extralen_get(swigCPtr, this);
  }

  public usb_config_descriptor() {
    this(LibusbJNI.new_usb_config_descriptor(), true);
  }

}
