/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_interface_descriptor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_interface_descriptor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_interface_descriptor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_interface_descriptor(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBLength(short value) {
    LibusbJNI.usb_interface_descriptor_bLength_set(swigCPtr, this, value);
  }

  public short getBLength() {
    return LibusbJNI.usb_interface_descriptor_bLength_get(swigCPtr, this);
  }

  public void setBDescriptorType(short value) {
    LibusbJNI.usb_interface_descriptor_bDescriptorType_set(swigCPtr, this, value);
  }

  public short getBDescriptorType() {
    return LibusbJNI.usb_interface_descriptor_bDescriptorType_get(swigCPtr, this);
  }

  public void setBInterfaceNumber(short value) {
    LibusbJNI.usb_interface_descriptor_bInterfaceNumber_set(swigCPtr, this, value);
  }

  public short getBInterfaceNumber() {
    return LibusbJNI.usb_interface_descriptor_bInterfaceNumber_get(swigCPtr, this);
  }

  public void setBAlternateSetting(short value) {
    LibusbJNI.usb_interface_descriptor_bAlternateSetting_set(swigCPtr, this, value);
  }

  public short getBAlternateSetting() {
    return LibusbJNI.usb_interface_descriptor_bAlternateSetting_get(swigCPtr, this);
  }

  public void setBNumEndpoints(short value) {
    LibusbJNI.usb_interface_descriptor_bNumEndpoints_set(swigCPtr, this, value);
  }

  public short getBNumEndpoints() {
    return LibusbJNI.usb_interface_descriptor_bNumEndpoints_get(swigCPtr, this);
  }

  public void setBInterfaceClass(short value) {
    LibusbJNI.usb_interface_descriptor_bInterfaceClass_set(swigCPtr, this, value);
  }

  public short getBInterfaceClass() {
    return LibusbJNI.usb_interface_descriptor_bInterfaceClass_get(swigCPtr, this);
  }

  public void setBInterfaceSubClass(short value) {
    LibusbJNI.usb_interface_descriptor_bInterfaceSubClass_set(swigCPtr, this, value);
  }

  public short getBInterfaceSubClass() {
    return LibusbJNI.usb_interface_descriptor_bInterfaceSubClass_get(swigCPtr, this);
  }

  public void setBInterfaceProtocol(short value) {
    LibusbJNI.usb_interface_descriptor_bInterfaceProtocol_set(swigCPtr, this, value);
  }

  public short getBInterfaceProtocol() {
    return LibusbJNI.usb_interface_descriptor_bInterfaceProtocol_get(swigCPtr, this);
  }

  public void setIInterface(short value) {
    LibusbJNI.usb_interface_descriptor_iInterface_set(swigCPtr, this, value);
  }

  public short getIInterface() {
    return LibusbJNI.usb_interface_descriptor_iInterface_get(swigCPtr, this);
  }

  public void setEndpoint(usb_endpoint_descriptor value) {
    LibusbJNI.usb_interface_descriptor_endpoint_set(swigCPtr, this, usb_endpoint_descriptor.getCPtr(value), value);
  }

  public usb_endpoint_descriptor getEndpoint() {
    long cPtr = LibusbJNI.usb_interface_descriptor_endpoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new usb_endpoint_descriptor(cPtr, false);
  }

  public void setExtra(SWIGTYPE_p_unsigned_char value) {
    LibusbJNI.usb_interface_descriptor_extra_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getExtra() {
    long cPtr = LibusbJNI.usb_interface_descriptor_extra_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setExtralen(int value) {
    LibusbJNI.usb_interface_descriptor_extralen_set(swigCPtr, this, value);
  }

  public int getExtralen() {
    return LibusbJNI.usb_interface_descriptor_extralen_get(swigCPtr, this);
  }

  public usb_interface_descriptor() {
    this(LibusbJNI.new_usb_interface_descriptor(), true);
  }

}
