/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_descriptor_header {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_descriptor_header(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_descriptor_header obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_descriptor_header(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBLength(short value) {
    LibusbJNI.usb_descriptor_header_bLength_set(swigCPtr, this, value);
  }

  public short getBLength() {
    return LibusbJNI.usb_descriptor_header_bLength_get(swigCPtr, this);
  }

  public void setBDescriptorType(short value) {
    LibusbJNI.usb_descriptor_header_bDescriptorType_set(swigCPtr, this, value);
  }

  public short getBDescriptorType() {
    return LibusbJNI.usb_descriptor_header_bDescriptorType_get(swigCPtr, this);
  }

  public usb_descriptor_header() {
    this(LibusbJNI.new_usb_descriptor_header(), true);
  }

}
