/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_ctrl_setup {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_ctrl_setup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_ctrl_setup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_ctrl_setup(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBRequestType(short value) {
    LibusbJNI.usb_ctrl_setup_bRequestType_set(swigCPtr, this, value);
  }

  public short getBRequestType() {
    return LibusbJNI.usb_ctrl_setup_bRequestType_get(swigCPtr, this);
  }

  public void setBRequest(short value) {
    LibusbJNI.usb_ctrl_setup_bRequest_set(swigCPtr, this, value);
  }

  public short getBRequest() {
    return LibusbJNI.usb_ctrl_setup_bRequest_get(swigCPtr, this);
  }

  public void setWValue(int value) {
    LibusbJNI.usb_ctrl_setup_wValue_set(swigCPtr, this, value);
  }

  public int getWValue() {
    return LibusbJNI.usb_ctrl_setup_wValue_get(swigCPtr, this);
  }

  public void setWIndex(int value) {
    LibusbJNI.usb_ctrl_setup_wIndex_set(swigCPtr, this, value);
  }

  public int getWIndex() {
    return LibusbJNI.usb_ctrl_setup_wIndex_get(swigCPtr, this);
  }

  public void setWLength(int value) {
    LibusbJNI.usb_ctrl_setup_wLength_set(swigCPtr, this, value);
  }

  public int getWLength() {
    return LibusbJNI.usb_ctrl_setup_wLength_get(swigCPtr, this);
  }

  public usb_ctrl_setup() {
    this(LibusbJNI.new_usb_ctrl_setup(), true);
  }

}
