/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_ctrl_setup {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_ctrl_setup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_ctrl_setup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_ctrl_setup(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBRequestType(short bRequestType) {
    LibusbJNI.set_usb_ctrl_setup_bRequestType(swigCPtr, bRequestType);
  }

  public short getBRequestType() {
    return LibusbJNI.get_usb_ctrl_setup_bRequestType(swigCPtr);
  }

  public void setBRequest(short bRequest) {
    LibusbJNI.set_usb_ctrl_setup_bRequest(swigCPtr, bRequest);
  }

  public short getBRequest() {
    return LibusbJNI.get_usb_ctrl_setup_bRequest(swigCPtr);
  }

  public void setWValue(int wValue) {
    LibusbJNI.set_usb_ctrl_setup_wValue(swigCPtr, wValue);
  }

  public int getWValue() {
    return LibusbJNI.get_usb_ctrl_setup_wValue(swigCPtr);
  }

  public void setWIndex(int wIndex) {
    LibusbJNI.set_usb_ctrl_setup_wIndex(swigCPtr, wIndex);
  }

  public int getWIndex() {
    return LibusbJNI.get_usb_ctrl_setup_wIndex(swigCPtr);
  }

  public void setWLength(int wLength) {
    LibusbJNI.set_usb_ctrl_setup_wLength(swigCPtr, wLength);
  }

  public int getWLength() {
    return LibusbJNI.get_usb_ctrl_setup_wLength(swigCPtr);
  }

  public usb_ctrl_setup() {
    this(LibusbJNI.new_usb_ctrl_setup(), true);
  }

}
