/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_endpoint_descriptor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_endpoint_descriptor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_endpoint_descriptor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_endpoint_descriptor(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBLength(short value) {
    LibusbJNI.usb_endpoint_descriptor_bLength_set(swigCPtr, this, value);
  }

  public short getBLength() {
    return LibusbJNI.usb_endpoint_descriptor_bLength_get(swigCPtr, this);
  }

  public void setBDescriptorType(short value) {
    LibusbJNI.usb_endpoint_descriptor_bDescriptorType_set(swigCPtr, this, value);
  }

  public short getBDescriptorType() {
    return LibusbJNI.usb_endpoint_descriptor_bDescriptorType_get(swigCPtr, this);
  }

  public void setBEndpointAddress(short value) {
    LibusbJNI.usb_endpoint_descriptor_bEndpointAddress_set(swigCPtr, this, value);
  }

  public short getBEndpointAddress() {
    return LibusbJNI.usb_endpoint_descriptor_bEndpointAddress_get(swigCPtr, this);
  }

  public void setBmAttributes(short value) {
    LibusbJNI.usb_endpoint_descriptor_bmAttributes_set(swigCPtr, this, value);
  }

  public short getBmAttributes() {
    return LibusbJNI.usb_endpoint_descriptor_bmAttributes_get(swigCPtr, this);
  }

  public void setWMaxPacketSize(int value) {
    LibusbJNI.usb_endpoint_descriptor_wMaxPacketSize_set(swigCPtr, this, value);
  }

  public int getWMaxPacketSize() {
    return LibusbJNI.usb_endpoint_descriptor_wMaxPacketSize_get(swigCPtr, this);
  }

  public void setBInterval(short value) {
    LibusbJNI.usb_endpoint_descriptor_bInterval_set(swigCPtr, this, value);
  }

  public short getBInterval() {
    return LibusbJNI.usb_endpoint_descriptor_bInterval_get(swigCPtr, this);
  }

  public void setBRefresh(short value) {
    LibusbJNI.usb_endpoint_descriptor_bRefresh_set(swigCPtr, this, value);
  }

  public short getBRefresh() {
    return LibusbJNI.usb_endpoint_descriptor_bRefresh_get(swigCPtr, this);
  }

  public void setBSynchAddress(short value) {
    LibusbJNI.usb_endpoint_descriptor_bSynchAddress_set(swigCPtr, this, value);
  }

  public short getBSynchAddress() {
    return LibusbJNI.usb_endpoint_descriptor_bSynchAddress_get(swigCPtr, this);
  }

  public void setExtra(SWIGTYPE_p_unsigned_char value) {
    LibusbJNI.usb_endpoint_descriptor_extra_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getExtra() {
    long cPtr = LibusbJNI.usb_endpoint_descriptor_extra_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setExtralen(int value) {
    LibusbJNI.usb_endpoint_descriptor_extralen_set(swigCPtr, this, value);
  }

  public int getExtralen() {
    return LibusbJNI.usb_endpoint_descriptor_extralen_get(swigCPtr, this);
  }

  public usb_endpoint_descriptor() {
    this(LibusbJNI.new_usb_endpoint_descriptor(), true);
  }

}
