/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_interface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_interface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_interface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_interface(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setAltsetting(usb_interface_descriptor value) {
    LibusbJNI.usb_interface_altsetting_set(swigCPtr, this, usb_interface_descriptor.getCPtr(value), value);
  }

  public usb_interface_descriptor getAltsetting() {
    long cPtr = LibusbJNI.usb_interface_altsetting_get(swigCPtr, this);
    return (cPtr == 0) ? null : new usb_interface_descriptor(cPtr, false);
  }

  public void setNum_altsetting(int value) {
    LibusbJNI.usb_interface_num_altsetting_set(swigCPtr, this, value);
  }

  public int getNum_altsetting() {
    return LibusbJNI.usb_interface_num_altsetting_get(swigCPtr, this);
  }

  public usb_interface() {
    this(LibusbJNI.new_usb_interface(), true);
  }

}
