/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_bus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_bus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_bus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_bus(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setNext(usb_bus next) {
    LibusbJNI.set_usb_bus_next(swigCPtr, usb_bus.getCPtr(next));
  }

  public usb_bus getNext() {
    long cPtr = LibusbJNI.get_usb_bus_next(swigCPtr);
    return (cPtr == 0) ? null : new usb_bus(cPtr, false);
  }

  public void setPrev(usb_bus prev) {
    LibusbJNI.set_usb_bus_prev(swigCPtr, usb_bus.getCPtr(prev));
  }

  public usb_bus getPrev() {
    long cPtr = LibusbJNI.get_usb_bus_prev(swigCPtr);
    return (cPtr == 0) ? null : new usb_bus(cPtr, false);
  }

  public void setDirname(String dirname) {
    LibusbJNI.set_usb_bus_dirname(swigCPtr, dirname);
  }

  public String getDirname() {
    return LibusbJNI.get_usb_bus_dirname(swigCPtr);
  }

  public void setDevices(usb_device devices) {
    LibusbJNI.set_usb_bus_devices(swigCPtr, usb_device.getCPtr(devices));
  }

  public usb_device getDevices() {
    long cPtr = LibusbJNI.get_usb_bus_devices(swigCPtr);
    return (cPtr == 0) ? null : new usb_device(cPtr, false);
  }

  public void setLocation(long location) {
    LibusbJNI.set_usb_bus_location(swigCPtr, location);
  }

  public long getLocation() {
    return LibusbJNI.get_usb_bus_location(swigCPtr);
  }

  public usb_bus() {
    this(LibusbJNI.new_usb_bus(), true);
  }

}
