/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_bus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_bus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_bus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_bus(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setNext(usb_bus value) {
    LibusbJNI.usb_bus_next_set(swigCPtr, this, usb_bus.getCPtr(value), value);
  }

  public usb_bus getNext() {
    long cPtr = LibusbJNI.usb_bus_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new usb_bus(cPtr, false);
  }

  public void setPrev(usb_bus value) {
    LibusbJNI.usb_bus_prev_set(swigCPtr, this, usb_bus.getCPtr(value), value);
  }

  public usb_bus getPrev() {
    long cPtr = LibusbJNI.usb_bus_prev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new usb_bus(cPtr, false);
  }

  public void setDirname(String value) {
    LibusbJNI.usb_bus_dirname_set(swigCPtr, this, value);
  }

  public String getDirname() {
    return LibusbJNI.usb_bus_dirname_get(swigCPtr, this);
  }

  public void setDevices(usb_device value) {
    LibusbJNI.usb_bus_devices_set(swigCPtr, this, usb_device.getCPtr(value), value);
  }

  public usb_device getDevices() {
    long cPtr = LibusbJNI.usb_bus_devices_get(swigCPtr, this);
    return (cPtr == 0) ? null : new usb_device(cPtr, false);
  }

  public void setLocation(long value) {
    LibusbJNI.usb_bus_location_set(swigCPtr, this, value);
  }

  public long getLocation() {
    return LibusbJNI.usb_bus_location_get(swigCPtr, this);
  }

  public void setRoot_dev(usb_device value) {
    LibusbJNI.usb_bus_root_dev_set(swigCPtr, this, usb_device.getCPtr(value), value);
  }

  public usb_device getRoot_dev() {
    long cPtr = LibusbJNI.usb_bus_root_dev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new usb_device(cPtr, false);
  }

  public usb_bus() {
    this(LibusbJNI.new_usb_bus(), true);
  }

}
