/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_hid_descriptor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_hid_descriptor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_hid_descriptor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_hid_descriptor(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBLength(short value) {
    LibusbJNI.usb_hid_descriptor_bLength_set(swigCPtr, this, value);
  }

  public short getBLength() {
    return LibusbJNI.usb_hid_descriptor_bLength_get(swigCPtr, this);
  }

  public void setBDescriptorType(short value) {
    LibusbJNI.usb_hid_descriptor_bDescriptorType_set(swigCPtr, this, value);
  }

  public short getBDescriptorType() {
    return LibusbJNI.usb_hid_descriptor_bDescriptorType_get(swigCPtr, this);
  }

  public void setBcdHID(int value) {
    LibusbJNI.usb_hid_descriptor_bcdHID_set(swigCPtr, this, value);
  }

  public int getBcdHID() {
    return LibusbJNI.usb_hid_descriptor_bcdHID_get(swigCPtr, this);
  }

  public void setBCountryCode(short value) {
    LibusbJNI.usb_hid_descriptor_bCountryCode_set(swigCPtr, this, value);
  }

  public short getBCountryCode() {
    return LibusbJNI.usb_hid_descriptor_bCountryCode_get(swigCPtr, this);
  }

  public void setBNumDescriptors(short value) {
    LibusbJNI.usb_hid_descriptor_bNumDescriptors_set(swigCPtr, this, value);
  }

  public short getBNumDescriptors() {
    return LibusbJNI.usb_hid_descriptor_bNumDescriptors_get(swigCPtr, this);
  }

  public usb_hid_descriptor() {
    this(LibusbJNI.new_usb_hid_descriptor(), true);
  }

}
