/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sf.libusb;

public class usb_device {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected usb_device(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(usb_device obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      LibusbJNI.delete_usb_device(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setNext(usb_device next) {
    LibusbJNI.set_usb_device_next(swigCPtr, usb_device.getCPtr(next));
  }

  public usb_device getNext() {
    long cPtr = LibusbJNI.get_usb_device_next(swigCPtr);
    return (cPtr == 0) ? null : new usb_device(cPtr, false);
  }

  public void setPrev(usb_device prev) {
    LibusbJNI.set_usb_device_prev(swigCPtr, usb_device.getCPtr(prev));
  }

  public usb_device getPrev() {
    long cPtr = LibusbJNI.get_usb_device_prev(swigCPtr);
    return (cPtr == 0) ? null : new usb_device(cPtr, false);
  }

  public void setFilename(String filename) {
    LibusbJNI.set_usb_device_filename(swigCPtr, filename);
  }

  public String getFilename() {
    return LibusbJNI.get_usb_device_filename(swigCPtr);
  }

  public void setBus(usb_bus bus) {
    LibusbJNI.set_usb_device_bus(swigCPtr, usb_bus.getCPtr(bus));
  }

  public usb_bus getBus() {
    long cPtr = LibusbJNI.get_usb_device_bus(swigCPtr);
    return (cPtr == 0) ? null : new usb_bus(cPtr, false);
  }

  public void setDescriptor(usb_device_descriptor descriptor) {
    LibusbJNI.set_usb_device_descriptor(swigCPtr, usb_device_descriptor.getCPtr(descriptor));
  }

  public usb_device_descriptor getDescriptor() {
    long cPtr = LibusbJNI.get_usb_device_descriptor(swigCPtr);
    return (cPtr == 0) ? null : new usb_device_descriptor(cPtr, false);
  }

  public void setConfig(usb_config_descriptor config) {
    LibusbJNI.set_usb_device_config(swigCPtr, usb_config_descriptor.getCPtr(config));
  }

  public usb_config_descriptor getConfig() {
    long cPtr = LibusbJNI.get_usb_device_config(swigCPtr);
    return (cPtr == 0) ? null : new usb_config_descriptor(cPtr, false);
  }

  public void setDev(SWIGTYPE_p_void dev) {
    LibusbJNI.set_usb_device_dev(swigCPtr, SWIGTYPE_p_void.getCPtr(dev));
  }

  public SWIGTYPE_p_void getDev() {
    long cPtr = LibusbJNI.get_usb_device_dev(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public usb_device() {
    this(LibusbJNI.new_usb_device(), true);
  }

}
